name: Deploy to Server!

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: SFTP Deploy
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -P 22 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} <<EOF
          cd ${{ secrets.FTP_SERVER_DIR }}
          put -r * .
          bye
          EOF
